CREATE PROCEDURE [dbo].[TipoInquilinoInsertar]
	@Descripcion VARCHAR(250),
	@Estado BIT

AS BEGIN
SET NOCOUNT ON
	BEGIN TRANSACTION TRANSAC
		BEGIN TRY
			INSERT INTO dbo.TipoInquilino(Descripcion, Estado) VALUES(@Descripcion, @Estado)
	COMMIT TRANSACTION TRANSAC
		  SELECT 0 AS CodeError, '' AS MsgError
		END TRY

BEGIN CATCH
	SELECT 
         ERROR_NUMBER() AS CodeError,
		 ERROR_MESSAGE() AS MsgError
   ROLLBACK TRANSACTION TRANSAC
END CATCH
END